# Generated by Django 5.1.7 on 2025-04-02 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('contacts', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('site', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('object_code', models.CharField(max_length=100)),
                ('floor', models.PositiveIntegerField()),
                ('building_count', models.PositiveIntegerField()),
                ('material', models.CharField(choices=[('brick', 'Brick'), ('panel', 'Panel'), ('monolithic', 'Monolithic'), ('other', 'Other')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_programs', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('has_balcony', models.BooleanField(default=False)),
                ('is_balcony_glazed', models.BooleanField(default=False)),
                ('building_start_date', models.DateField()),
                ('home_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], max_length=50)),
                ('bathroom_type', models.CharField(choices=[('combined', 'Combined'), ('separate', 'Separate')], max_length=50)),
                ('security', models.CharField(choices=[('security', 'Security'), ('concierge', 'Concierge'), ('none', 'None')], max_length=50)),
                ('parking_type', models.CharField(choices=[('underground', 'Underground'), ('ground', 'Ground'), ('none', 'None')], max_length=50)),
                ('elevator_type', models.CharField(choices=[('passenger', 'Passenger'), ('cargo', 'Cargo'), ('both', 'Both'), ('none', 'None')], max_length=50)),
                ('apartment_types', models.JSONField(default=list)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.builder')),
            ],
        ),
    ]
