# Generated by Django 5.1.7 on 2025-04-02 01:21

import apartments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apartments.models.upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathroom_type',
            field=models.CharField(choices=[('combined', 'Совмещенный'), ('separate', 'Раздельный')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='elevator_type',
            field=models.CharField(choices=[('passenger', 'Пассажирский'), ('cargo', 'Грузовой'), ('both', 'Грузопассажирский'), ('none', 'Отсутствует')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='home_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='material',
            field=models.CharField(choices=[('brick', 'Кирпич'), ('panel', 'Панель'), ('monolithic', 'Монолит'), ('other', 'Другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking_type',
            field=models.CharField(choices=[('underground', 'Подземная'), ('ground', 'Наземная'), ('none', 'Отсутствует')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='security',
            field=models.CharField(choices=[('security', 'Охрана'), ('concierge', 'Консьерж'), ('none', 'Отсутствует')], max_length=50),
        ),
    ]
