# Generated by Django 5.1.7 on 2025-04-02 01:26

import apartments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_uploadedfile_alter_apartment_bathroom_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['name'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='builder',
            options={'ordering': ['name'], 'verbose_name': 'Застройщик', 'verbose_name_plural': 'Застройщики'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_types',
            field=models.JSONField(default=list, verbose_name='Типы квартир'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='available_programs',
            field=models.JSONField(default=list, verbose_name='Доступные программы'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathroom_type',
            field=models.CharField(choices=[('combined', 'Совмещенный'), ('separate', 'Раздельный')], max_length=50, verbose_name='Тип санузла'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.builder', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building_count',
            field=models.PositiveIntegerField(verbose_name='Количество зданий'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building_start_date',
            field=models.DateField(verbose_name='Дата начала строительства'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='conditions',
            field=models.JSONField(default=list, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='elevator_type',
            field=models.CharField(choices=[('passenger', 'Пассажирский'), ('cargo', 'Грузовой'), ('both', 'Грузопассажирский'), ('none', 'Отсутствует')], max_length=50, verbose_name='Тип лифта'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='end_date',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Есть балкон'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='home_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом')], max_length=50, verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='images',
            field=models.JSONField(default=list, verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_balcony_glazed',
            field=models.BooleanField(default=False, verbose_name='Балкон остеклен'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='material',
            field=models.CharField(choices=[('brick', 'Кирпич'), ('panel', 'Панель'), ('monolithic', 'Монолит'), ('other', 'Другое')], max_length=50, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='object_code',
            field=models.CharField(max_length=100, verbose_name='Код объекта'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking_type',
            field=models.CharField(choices=[('underground', 'Подземная'), ('ground', 'Наземная'), ('none', 'Отсутствует')], max_length=50, verbose_name='Тип паркинга'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='security',
            field=models.CharField(choices=[('security', 'Охрана'), ('concierge', 'Консьерж'), ('none', 'Отсутствует')], max_length=50, verbose_name='Охрана'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала продаж'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='contacts',
            field=models.TextField(verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='icon',
            field=models.URLField(blank=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='site',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=apartments.models.upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
