# Generated by Django 5.1.7 on 2025-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на подтверждающий документ'),
        ),
    ]
