# Generated by Django 5.1.7 on 2025-04-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='customuser',
        ),
    ]
