# Generated by Django 5.1.7 on 2025-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_rename_customuser_application_user_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
